### ISSUE TITLE
Template path in project

### ISSUE THREAD

**Issue by sander-spruit** [yeasir01/bpac-js#7]
Hi,
Great plugin, looking forward to using it! However, it's currently not working for me, as it cannot find the template through the template path. I have an angular project, and the template path is never actually found. Is there a fix available making it possible to a working path? Thanks!

**Comment by yeasir01** [comment]
> Hi, Great plugin, looking forward to using it! However, it's currently not working for me, as it cannot find the template through the template path. I have an angular project, and the template path is never actually found. Is there a fix available making it possible to a working path? Thanks!

Great to hear.
1. Make sure the printer is installed and working (ex. can print from template)
2. Make sure you have the bPac client installed. This enables communication between the browser plugin and the print driver.
3. Install the Brother bPac Extension and make sure it's enabled.
Chrome Ext Link: https://chromewebstore.google.com/detail/ilpghlfadkjifilabejhhijpfphfcfhb
4: Use a UNC or absolute path for the template location.

If all that checks out please post a snippet of the code that's not working.

**Comment by sander-spruit** [comment]
Step 4 is the issue. Because it requires a UNC or absolute path, I cannot integrate it into an app, since that would require a relative path. Is a fix available?

**Comment by yeasir01** [comment]
Could you provide more context for what you’re trying to achieve? The UNC and absolute paths covers most cases if used in the proper context.

**Comment by yeasir01** [comment]
This issue has been closed due to inactivity. If you would like to discuss this issue further, please reopen the issue.
