### ISSUE TITLE
Documentation clarifcation

### ISSUE THREAD

**Issue by sander-spruit** [yeasir01/bpac-js#8]
This tool will only ever work on Windows OS. Please clarify! bpac is not working on MacOS

**Comment by yeasir01** [comment]
Welcome sander-spruit. Yes, the Brother Bpac client is only available for Windows according to Brother's support website.
[https://support.brother.com/g/s/es/dev/en/bpac/environment/index.html?c=eu_ot&lang=en&navi=offall&comple=on&redirect=on#os](url)

**Comment by yeasir01** [comment]
This issue has been closed due to inactivity. If you would like to discuss this issue further, please reopen the issue.
